name: 差分解析とメール送信

on:
  push:
    branches:
      - main

jobs:
  analyze:
    permissions:
      actions: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: git diff を取得
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          git diff HEAD^ HEAD > diff.txt

      - name: 依存関係をインストール
        run: pip install openai

      - name: OpenAIで差分を解析
        id: analyze
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
            python scripts/analyze_diff.py diff.txt analysis.txt
            # delimiterがanalysis.txtに含まれている場合は除去
            sed '/^__END_OF_ANALYSIS__$/d' analysis.txt > sanitized_analysis.txt
            echo "analysis<<__END_OF_ANALYSIS__" >> $GITHUB_OUTPUT
            cat sanitized_analysis.txt >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "__END_OF_ANALYSIS__" >> $GITHUB_OUTPUT

      - name: 解析結果をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: diff-analysis
          path: analysis.txt

      - name: 承認を待機
        id: approve
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}

      - name: 手動承認の出力を記録
        run: echo "approve.approval-status=${{ steps.approve.outputs['approval-status'] }}"

      - name: 解析結果をメール送信
        if: ${{ steps.approve.outputs['approval-status'] == 'approved' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: コミット ${{ github.sha }} の差分解析
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
          body: |
            コミット ${{ github.sha }} の差分解析:

            ${{ steps.analyze.outputs.analysis }}
